# Spring Boot Configuration for CRM System
# Production-ready configuration for containerized deployment

server:
  port: 8080
  shutdown: graceful
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

spring:
  application:
    name: crm-system
    
  profiles:
    active: production
    
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/crm_db}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:changeme123!}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      leak-detection-threshold: 60000
      
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
        jdbc:
          batch_size: 20
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
            
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=10000,expireAfterAccess=300s
      
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC
    
  security:
    basic:
      enabled: false
      
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      show-components: always
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.9, 0.95, 0.99
        
logging:
  level:
    root: INFO
    com.company.crm: INFO
    org.springframework.web: WARN
    org.hibernate: WARN
  pattern:
    console: "%d{ISO8601} [%thread] %-5level [%logger{36}] - %msg%n"
    file: "%d{ISO8601} [%thread] %-5level [%logger{36}] - %msg%n"
  file:
    name: /app/logs/crm-system.log
    max-size: 100MB
    max-history: 30
    
# Custom application properties
crm:
  features:
    analytics: true
    reporting: true
    integrations: true
  performance:
    cache-ttl: 300
    batch-size: 100
    max-connections: 50
  security:
    jwt-secret: ${JWT_SECRET:your-secret-key}
    token-expiration: 86400
    
# Actuator info
info:
  app:
    name: CRM System
    description: Modernized Customer Relationship Management System
    version: 2.1.0
    encoding: UTF-8
    java:
      version: 17
